language: python
python:
  - "2.7"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  coverage run tests.py
after_success:
  coveralls
notifications:
  email: false
